const PHOTOS_COUNT = 25;
const AVATAR_WIDTH = 35;
const AVATAR_HEIGHT = 35;
const MIN_HASHTAGS_COUNT = 1;
const MAX_HASHTAGS_COUNT = 5;
const MAX_LENGTH_COMMENT = 140;
const MIN_UNIQUE_PHOTOS_COUNT = 1;
const MAX_UNIQUE_PHOTOS_COUNT = 10;
const RERENDER_DELAY = 500;

export {PHOTOS_COUNT,
  AVATAR_WIDTH,
  AVATAR_HEIGHT,
  MAX_HASHTAGS_COUNT,
  MIN_HASHTAGS_COUNT,
  MAX_LENGTH_COMMENT,
  MIN_UNIQUE_PHOTOS_COUNT,
  MAX_UNIQUE_PHOTOS_COUNT,
  RERENDER_DELAY};
