const PHOTOS_COUNT = 25;
const AVATAR_WIDTH = 35;
const AVATAR_HEIGHT = 35;
const MAX_HASHTAG_LENGTH = 20;
const MAX_HASHTAGS_COUNT = 5;
const MAX_LENGTH_COMMENT = 140;
const MIN_UNIQUE_PHOTOS_COUNT = 1;
const MAX_UNIQUE_PHOTOS_COUNT = 10;
const RERENDER_DELAY = 500;
const ALERT_SHOW_TIME = 5000;
const COMMENTS_CHUNK_SIZE = 5;
const ESCAPE_KEYDOWN = 'Escape';


export {PHOTOS_COUNT,
  AVATAR_WIDTH,
  AVATAR_HEIGHT,
  MAX_HASHTAGS_COUNT,
  MAX_LENGTH_COMMENT,
  MIN_UNIQUE_PHOTOS_COUNT,
  MAX_UNIQUE_PHOTOS_COUNT,
  RERENDER_DELAY,
  ALERT_SHOW_TIME,
  COMMENTS_CHUNK_SIZE,
  MAX_HASHTAG_LENGTH,
  ESCAPE_KEYDOWN};
